---
- name: Deploy MuleSoft Based on Tower Input
  hosts: "{{ parsed_host }}"
  become: true
  vars:
    mule_version: "4.9.3"
    mule_root_dir: "/apps"
    mule_base_dir: "/apps/mulesoft"
    mule_runtime_dir: "/apps/mulesoft/runtime"
    mule_scripts_dir: "/apps/mulesoft/scripts"
    binary_url: "http://10.220.36.44/pub/.tools/mule-ee-distribution-{{ mule_version }}.tar.gz"
    binary_file: "mule-ee-distribution-{{ mule_version }}.tar.gz"
    download_path: "{{ mule_scripts_dir }}/{{ binary_file }}"
    mule_user_top: "muleins"
    mule_group_top: "mulesvc"
    mule_user_inner: "muleins"
    mule_group_inner: "muleins"

    # Parse string like "prod_External_pwlvs01mul001"
    parts: "{{ env_businessgroup_hostname.split('_') }}"
    parsed_env: "{{ parts[0] }}"
    parsed_group: "{{ parts[1] | lower }}-service"
    parsed_host: "{{ parts[2] }}"
    license_type: "{{ 'prod' if parsed_env in ['prod', 'dr'] else 'non-prod' }}"

  tasks:

    - name: Ensure /apps directory (root:root)
      file:
        path: "{{ mule_root_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create /apps/mulesoft (muleins:mulesvc)
      file:
        path: "{{ mule_base_dir }}"
        state: directory
        owner: "{{ mule_user_top }}"
        group: "{{ mule_group_top }}"
        mode: '0755'

    - name: Create /apps/mulesoft/runtime (muleins:muleins)
      file:
        path: "{{ mule_runtime_dir }}"
        state: directory
        owner: "{{ mule_user_inner }}"
        group: "{{ mule_group_inner }}"
        mode: '0755'

    - name: Create /apps/mulesoft/scripts (muleins:muleins)
      file:
        path: "{{ mule_scripts_dir }}"
        state: directory
        owner: "{{ mule_user_inner }}"
        group: "{{ mule_group_inner }}"
        mode: '0755'

    - name: Download MuleSoft binary
      get_url:
        url: "{{ binary_url }}"
        dest: "{{ download_path }}"
        mode: '0644'
        owner: "{{ mule_user_inner }}"
        group: "{{ mule_group_inner }}"

    - name: Extract MuleSoft binary for business group
      unarchive:
        src: "{{ download_path }}"
        dest: "{{ mule_runtime_dir }}/{{ mule_version }}/{{ parsed_group }}"
        remote_src: yes
        owner: "{{ mule_user_inner }}"
        group: "{{ mule_user_inner }}"

    - name: Upload environment-specific license
      copy:
        src: "files/{{ license_type }}-license.lic"
        dest: "{{ mule_runtime_dir }}/{{ mule_version }}/{{ parsed_group }}/conf/license.lic"
        owner: "{{ mule_user_inner }}"
        group: "{{ mule_user_inner }}"
        mode: '0644'

    - name: Start MuleSoft
      shell: "{{ mule_runtime_dir }}/{{ mule_version }}/{{ parsed_group }}/bin/mule start"
      args:
        executable: /bin/bash
