---
- name: Install MuleSoft Runtime and Start Services
  hosts: all
  become: true
  vars:
    mule_version: "4.9.3"
    mule_root_dir: "/apps"
    mule_base_dir: "/apps/mulesoft"
    mule_runtime_dir: "/apps/mulesoft/runtime"
    mule_scripts_dir: "/apps/mulesoft/scripts"
    mule_services:
      - external-service
      - digital-service
      - teller-service
      - abcs-service
    binary_url: "http://10.220.36.44/pub/.tools/mule-ee-distribution-{{ mule_version }}.tar.gz"
    binary_file: "mule-ee-distribution-{{ mule_version }}.tar.gz"
    download_path: "{{ mule_scripts_dir }}/{{ binary_file }}"
    mule_user_top: "muleins"
    mule_group_top: "mulesvc"
    mule_user_inner: "muleins"
    mule_group_inner: "muleins"

  tasks:

    - name: Create /apps directory (root:root)
      file:
        path: "{{ mule_root_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create /apps/mulesoft directory (muleins:mulesvc)
      file:
        path: "{{ mule_base_dir }}"
        state: directory
        owner: "{{ mule_user_top }}"
        group: "{{ mule_group_top }}"
        mode: '0755'

    - name: Create /apps/mulesoft/runtime directory (muleins:muleins)
      file:
        path: "{{ mule_runtime_dir }}"
        state: directory
        owner: "{{ mule_user_inner }}"
        group: "{{ mule_group_inner }}"
        mode: '0755'

    - name: Create /apps/mulesoft/scripts directory (muleins:muleins)
      file:
        path: "{{ mule_scripts_dir }}"
        state: directory
        owner: "{{ mule_user_inner }}"
        group: "{{ mule_group_inner }}"
        mode: '0755'

    - name: Download MuleSoft binary into scripts directory
      get_url:
        url: "{{ binary_url }}"
        dest: "{{ download_path }}"
        mode: '0644'
        owner: "{{ mule_user_inner }}"
        group: "{{ mule_group_inner }}"

    - name: Extract MuleSoft binary for each service
      unarchive:
        src: "{{ download_path }}"
        dest: "{{ mule_runtime_dir }}/{{ mule_version }}/{{ item }}"
        remote_src: yes
        owner: "{{ mule_user_inner }}"
        group: "{{ mule_group_inner }}"
      loop: "{{ mule_services }}"

    - name: Copy environment-specific MuleSoft license file
      copy:
        src: "files/{{ ansible_environment }}-license.lic"
        dest: "{{ mule_runtime_dir }}/{{ mule_version }}/{{ item }}/conf/license.lic"
        owner: "{{ mule_user_inner }}"
        group: "{{ mule_group_inner }}"
        mode: '0644'
      loop: "{{ mule_services }}"
      when: ansible_environment in ['prod', 'non-prod']

    - name: Start Mule application for each business group
      shell: "{{ mule_runtime_dir }}/{{ mule_version }}/{{ item }}/bin/mule start"
      args:
        executable: /bin/bash
      loop: "{{ mule_services }}"
